---
title: "HPR Poll 1"
author: "Dominic Skinnion"
date: "4/10/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
poll1 <- read.csv("HODP x HPR_April 10, 2021_20.31.csv") %>%
  tail(-3) %>% 
  select("Finished",
         "ResponseId",
         starts_with("Q"))
```

```{r}
poll2 <- poll1

poll2[poll2 == "Strongly Disagree"] = -2
poll2[poll2 == "Disagree"] = -2
poll2[poll2 == "Neutral"] = 0
poll2[poll2 == "Agree"] = 1
poll2[poll2 == "Strongly Agree"] = 2

poll2 <- poll2 %>%
  mutate(biden = as.numeric(Q1),
         integrity = as.numeric(Q2),
         sec_imp = as.numeric(Q3),
         false_info = as.numeric(Q4),
         mjt = as.numeric(Q5),
         fraud_platform = as.numeric(Q6),
         party_trump = as.numeric(Q7),
         trump_platform = as.numeric(Q8),
         rep_platform = as.numeric(Q9),
         prof_west = as.numeric(Q10),
         op_soc = as.numeric(Q11),
         op_acad = as.numeric(Q12),
         class = as.numeric(Q22),
         gender = Q20,
         race = Q21)

```

```{r}
poll2 %>%
  ggplot(aes(x = biden)) +
  geom_bar() +
  labs(title = "I approve of how Joe Biden has handled his job as President.",
       x = "Approval",
       y = "Number of respondents")

poll2 %>%
  ggplot(aes(x = integrity)) +
  geom_bar(aes(y = ..prop..))

poll2 %>%
  ggplot(aes(x = sec_imp)) +
  geom_bar(aes(y = ..prop..))

poll2 %>%
  ggplot(aes(x = false_info)) +
  geom_bar(aes(y = ..prop..))

poll2 %>%
  ggplot(aes(x = mjt)) +
  geom_bar(aes(y = ..prop..))

poll2 %>%
  ggplot(aes(x = fraud_platform)) +
  geom_bar(aes(y = ..prop..))

poll2 %>%
  ggplot(aes(x = party_trump)) +
  geom_bar(aes(y = ..prop..))

poll2 %>%
  ggplot(aes(x = trump_platform)) +
  geom_bar(aes(y = ..prop..))

poll2 %>%
  ggplot(aes(x = rep_platform)) +
  geom_bar(aes(y = ..prop..))

poll2 %>%
  ggplot(aes(x = prof_west)) +
  geom_bar(aes(y = ..prop..))

poll2 %>%
  ggplot(aes(x = op_soc)) +
  geom_bar(aes(y = ..prop..))

poll2 %>%
  ggplot(aes(x = op_acad)) +
  geom_bar(aes(y = ..prop..))

poll2 %>%
  ggplot(aes(x = race)) +
  geom_bar() +
  coord_flip()
```

***Reweight based on race***

```{r}
poll2 %>%
  ggplot(aes(x = biden, y = integrity)) +
  geom_jitter(width = 0.1) +
  geom_smooth(method = 'lm')

poll2 %>%
  ggplot(aes(x = biden, y = false_info)) +
  geom_jitter(width = 0.1) +
  geom_smooth(method = 'lm')

poll2 %>%
  ggplot(aes(x = biden, y = op_soc)) +
  geom_jitter(width = 0.1) +
  geom_smooth(method = 'lm')

poll2 %>%
  ggplot(aes(x = biden, y = op_acad)) +
  geom_jitter(width = 0.1) +
  geom_smooth(method = 'lm')

poll2 %>%
  ggplot(aes(x = prof_west, y = race)) +
  geom_jitter(width = 0.1, alpha = 0.3)
```

```{r}
report <- read_csv("Default Report.csv")
```