---
title: "cleaning data"
author: "Angie Shin"
output: html_document
--- 

```{r setup, include=F}
knitr::opts_chunk$set(echo=F)
library(tidyverse)
library(janitor)

load("pre.rda")
pre_raw <- da37024.0001 %>% 
  clean_names() 

pre <- pre_raw %>% 
  select(id = respid,
         wgt = pweight,
         ethnicity = rethnic, 
         racegroup = race,
         state = rstate,
         gender = s7,
         education = s8,
         nativity1 = q1_3a,
         nativity2 = q1_3b,
         legality = q1_4,
         income1 = q8_15,
         income2 = q8_16,
         age1 = s5a,
         age2 = q8_19,
         reg = q4_1,
         votepred = q4_5a,
         votelean = q4_5e,
         party = q7_1,
         partycloser1 = q7_4a,
         partycloser2 = q7_4b,
         favorbo = q4_11c,
         favordt = q4_11d,
         favorhc = q4_11e,
         p1 = q6_5_1,
         p2 = q6_5_2,
         p3 = q6_5_3,
         p4 = q6_5_4,
         p5 = q6_5_5,
         p6 = q6_5_6,
         p7 = q6_5_7,
         media1 = q3_3a,
         media2 = q3_3b,
         soc1 = q6_1a,
         soc2 = q6_1d)

load("post.rda")
post_raw <- da37380.0001 %>% 
  clean_names()

post <- post_raw %>% 
  select(id = respid,
         wgt = nweightnativity,
         ethnicity = rethnicx,
         racegroup = race,
         state = rstate,
         gender = s7,
         education = s8,
         nativity1 = q1_3a,
         nativity2 = q1_3b,
         legality = q1_4,
         income1 = q10_15,
         income2 = q10_16,
         age1 = age2,
         age2 = q10_19,
         reg = q2_3,
         vote = q2_4,
         voteres = q2_4a,
         party = pid4,
         partycloser1 = q10_0d,
         partycloser2 = q10_0e,
         favorbo = q2_2c,
         favordt = q2_2a,
         favorhc = q2_2b,
         contact1 = q2_6,
         contact2 = q2_7,
         e1 = q3_6_a,
         e2 = q3_6_b,
         e3 = q3_6_c,
         e4 = q3_6_d,
         e5 = q3_6_f,
         e6 = q3_6_g,
         i1 = q5_8_a,
         i2 = q5_8_b,
         i3 = q5_8_c,
         i4 = q5_8_d,
         mi1 = q5_1_b,
         mi2 = q5_1_c,
         mi3 = q5_1_d,
         mi4 = q5_1_e,
         mi5 = q5_1_g,
         mi6 = q5_1_h,
         mi7 = q5_1_i,
         mi8 = q5_1_j,
         mi9 = q5_1_k,
         ma1 = q5_2_a,
         ma2 = q5_2_b,
         ma3 = q5_2_c,
         ma4 = q5_2_d,
         ma5 = q5_2_e,
         ma6 = q5_2_f,
         ma7 = q5_2_g,
         identity = q4_101)

# write_csv(pre, "pre.csv")
# write_csv(post, "post.csv")
```

```{r cleaning}
pre_aa <- pre %>% 
  filter(racegroup %in% c("(1) ASIAN AMERICAN", "(02) NHPI"),
         ethnicity != "(09) Laotian",
         ethnicity != "(23) Taiwanese") %>% 
  mutate_at(vars(p1, p2, p3, p4, p5, p6, p7), ~ as.character(.x),) %>% 
  mutate_at(vars(p1, p2, p3, p4, p5, p6, p7), ~ case_when(.x == "(1) Support" ~ "Support",
                                                          .x == "(2) Oppose" ~ "Oppose")) %>% 
  mutate_at(vars(favorhc, favordt), ~ case_when(.x == "(1) Very unfavorable" ~ "--",
                                                .x == "(2) Somewhat unfavorable" ~ "-",
                                                .x == "(3) Somewhat favorable" ~ "+",
                                                .x == "(4) Very favorable" ~ "++",
                                                .x == "(5) No opinion" ~ "Neutral")) %>% 
  mutate_at(vars(favorhc, favordt), ~ factor(.x, c("++", "+", "Neutral", "-", "--"))) %>% 
  mutate(income2 = case_when(income1 == "(1) Up to $20,000" ~ "(1) less than $50,000",
                             income1 == "(2) $20,000 to $50,000" ~ "(1) less than $50,000",
                             income1 == "(3) $50,000 to $75,000" ~ "(2) $50,000 to $100,000",
                             income1 == "(4) $75,000 to $100,000" ~ "(2) $50,000 to $100,000",
                             income1 == "(5) $100,000 to $125,000" ~ "(3) more than $100,000",
                             income1 == "(6) $125,000 to $250,000" ~ "(3) more than $100,000"),
         income2 = factor(income2, levels = c("(3) more than $100,000", 
                                              "(2) $50,000 to $100,000", 
                                              "(1) less than $50,000")),
         party = case_when(party == "(01) Democrat" ~ "D",
                           party == "(02) Republican" ~ "R"),
         votepred = case_when(votepred == "(1) Clinton" ~ "HC",
                              votepred == "(2) Trump" ~ "DT"),
         media1 = case_when(media1 == "(1) RETHNIC: or Asian American more" ~ "AA",
                            media1 == "(2) Mainstream American more" ~ "AM",
                            media1 == "(3) DO NOT READ  Both equally" ~ "Both")) %>% 
  filter(!is.na(income2))

post_aa <- post %>% 
  filter(racegroup %in% c("(1) Asian American", "(2) Pacific Islander"),
         ethnicity != "(01) Bangladeshi",
         ethnicity != "(10) Pakistani",
         ethnicity != "(12) Native Hawaiian",
         ethnicity != "(13) Samoan",
         ethnicity != "(16) Fijian") %>% 
  mutate_at(vars(e1, e2, e3, e4, e5, e6,
                 i1, i2, i3, i4), ~ case_when(.x == "(1) Strongly agree" ~ "Strong Agree",
                                              .x == "(2) Somewhat agree" ~ "Agree",
                                              .x == "(3) Neither" ~ "Neutral",
                                              .x == "(4) Somewhat disagree" ~ "Disagree",
                                              .x == "(5) Strongly disagree" ~ "Strong Disagree")) %>% 
  mutate_at(vars(e1, e2, e3, e4, e5, e6,
                 i1, i2, i3, i4), ~ factor(.x, levels = c("Srong Agree", "Agree", "Neutral",
                                                          "Disagree", "Strong Disagree"))) %>% 
  mutate_at(vars(favorhc, favordt), ~ case_when(.x == "(1) Very unfavorable" ~ "--",
                                                .x == "(2) Somewhat unfavorable" ~ "-",
                                                .x == "(3) Somewhat favorable" ~ "+",
                                                .x == "(4) Very favorable" ~ "++",
                                                .x == "(5) No opinion" ~ "Neutral")) %>% 
  mutate_at(vars(favorhc, favordt), ~ factor(.x, c("++", "+", "Neutral", "-", "--"))) %>% 
  mutate(income2 = case_when(income1 == "(1) Up to $20,000" ~ "(1) less than $50,000",
                             income1 == "(2) $20,000 to $50,000" ~ "(1) less than $50,000",
                             income1 == "(3) $50,000 to $75,000" ~ "(2) $50,000 to $100,000",
                             income1 == "(4) $75,000 to $100,000" ~ "(2) $50,000 to $100,000",
                             income1 == "(5) $100,000 to $125,000" ~ "(3) more than $100,000",
                             income1 == "(6) $125,000 to $250,000" ~ "(3) more than $100,000"),
         income2 = factor(income2, levels = c("(3) more than $100,000", 
                                              "(2) $50,000 to $100,000", 
                                              "(1) less than $50,000")),
         party = case_when(party == "(1) Democrat" ~ "D",
                           party == "(2) Republican" ~ "R"),
         voteres = case_when(voteres == "(1) Clinton" ~ "HC",
                             voteres == "(2) Trump" ~ "DT"),
         identity = case_when(identity == "(1) Asian American" ~ "AA",
                              identity == "(2) ANSWERFROM(RETHNIC)" ~ "Asian",
                              identity == "(3) ANSWERFROM(RETHNIC) American" ~ "AA",
                              identity == "(4) Asian" ~ "Asian",
                              identity == "(5) American" ~ "American",
                              identity == "(6) Other" ~ "None",
                              identity == "(7) None of these" ~ "None")) %>% 
  filter(!is.na(income2))
```