---
title: "DPI 610 Final Project"
subtitle: "AAPI Voices on the 2016 Presidential Election: Intersected by Socioeconomic Standing"
date: "May 4, 2021"
author: "Angie Shin"
output: pdf_document
--- 

# Introduction

Asian Americans and Pacific Islanders have been the most quickly growing racial demographic in the United States for the past twenty years. The AAPI communities claim an average growth of 600,000 registered voters per presidential election cycle, over 700 AAPI-serving organizations participating in National Voter Registration Day in September 2016, and an increase in Congressional candidates from 10 in 2010 to 30 in 2012 and 40 in 2016. While the AAPI communities face racist stereotypes of passiveness in civic engagement and political infrastructures, AAPI voices are strongly active in reality. 

The National Asian American Survey (NAAS) is a scientific and nonpartisan effort to poll the opinions of Asian Americans and Pacific Islanders. Its significance lies in their careful measurement of ethnicities beyond the monolithic "Asian" label that the vast majority of public opinion surveys have normalized, when finding public opinion results at an ethnically granular level can actually reveal important lessons about the AAPI communities and experiences. This project will concern the 2016 public opinion surveys that the NAAS has organized before and after the 2016 presidential election, to measure AAPI political opinions intentionally and spotlight them in a deliberately academic manner in order to help close the gap in research and academia on AAPI experiences. The purpose of this project specifically will involve the socioeconomic standing of survey respondents, to investigate how income level and socioeconomic status affects AAPI experiences and policy views.

# Dataset

The 2016 National Asian American Survey is composed of two waves. Individual-level data from the Fall 2016 National Asian American Survey (pre-election) was fielded from August through October 2016. Individual-level data from the NAAS 2016 Post-Election Survey was fielded from November 2016 through February 2017. For both surveys, the NAAS collaborated with Catalist, a for-profit corporation based in Washington, D.C. that operates a voter database and provides data and data-related services to progressive organizations, to utilize registered voter and commercial vendor samples; these were classified according to a variety of ethnicity variables. The 2016 NAAS Pre-Election Survey conducted 2,238 telephone interviews to AAPI adults (respondents were required to be 18 years of age or older to proceed with the survey) between August 10 and September 29, 2016. The 2016 NAAS Post-Election Survey conducted 4,393 telephone interviews to AAPI adults (respondents were required to be 18 years of age or older to proceed with the survey) between November 10, 2016 and March 2, 2017. The variable codebook and survey questionnaire for the Pre-Election survey are available [here](https://github.com/shinangie/gov1003/tree/main/final/data/ICPSR_37024/DS0001), and the variable codebook and survey questionnaire for the Post-Election survey are available [here](https://github.com/shinangie/gov1003/tree/main/final/data/ICPSR_37380/DS0001). 

```{r setup, include=F}
knitr::opts_chunk$set(include=F, echo=F)
library(tidyverse)
library(janitor)

load("pre.rda")
pre_raw <- da37024.0001 %>% 
  clean_names() 

pre <- pre_raw %>% 
  select(id = respid,
         wgt = pweight,
         ethnicity = rethnic, 
         racegroup = race,
         state = rstate,
         gender = s7,
         education = s8,
         nativity1 = q1_3a,
         nativity2 = q1_3b,
         legality = q1_4,
         income1 = q8_15,
         income2 = q8_16,
         age1 = s5a,
         age2 = q8_19,
         reg = q4_1,
         votepred = q4_5a,
         votelean = q4_5e,
         party = q7_1,
         partycloser1 = q7_4a,
         partycloser2 = q7_4b,
         favorbo = q4_11c,
         favordt = q4_11d,
         favorhc = q4_11e,
         p1 = q6_5_1,
         p2 = q6_5_2,
         p3 = q6_5_3,
         p4 = q6_5_4,
         p5 = q6_5_5,
         p6 = q6_5_6,
         p7 = q6_5_7,
         media1 = q3_3a,
         media2 = q3_3b,
         soc1 = q6_1a,
         soc2 = q6_1d)

load("post.rda")
post_raw <- da37380.0001 %>% 
  clean_names()

post <- post_raw %>% 
  select(id = respid,
         wgt = nweightnativity,
         ethnicity = rethnicx,
         racegroup = race,
         state = rstate,
         gender = s7,
         education = s8,
         nativity1 = q1_3a,
         nativity2 = q1_3b,
         legality = q1_4,
         income1 = q10_15,
         income2 = q10_16,
         age1 = age2,
         age2 = q10_19,
         reg = q2_3,
         vote = q2_4,
         voteres = q2_4a,
         party = pid4,
         partycloser1 = q10_0d,
         partycloser2 = q10_0e,
         favorbo = q2_2c,
         favordt = q2_2a,
         favorhc = q2_2b,
         contact1 = q2_6,
         contact2 = q2_7,
         e1 = q3_6_a,
         e2 = q3_6_b,
         e3 = q3_6_c,
         e4 = q3_6_d,
         e5 = q3_6_f,
         e6 = q3_6_g,
         i1 = q5_8_a,
         i2 = q5_8_b,
         i3 = q5_8_c,
         i4 = q5_8_d,
         mi1 = q5_1_b,
         mi2 = q5_1_c,
         mi3 = q5_1_d,
         mi4 = q5_1_e,
         mi5 = q5_1_g,
         mi6 = q5_1_h,
         mi7 = q5_1_i,
         mi8 = q5_1_j,
         mi9 = q5_1_k,
         ma1 = q5_2_a,
         ma2 = q5_2_b,
         ma3 = q5_2_c,
         ma4 = q5_2_d,
         ma5 = q5_2_e,
         ma6 = q5_2_f,
         ma7 = q5_2_g)

write_csv(pre, "pre.csv")
write_csv(post, "post.csv")
```

## Demographic Information

For both the Pre-Election and the Post-Election surveys, I measured the following variables:

* "id"
    * Respondent ID
* "wgt"
    * Sampling weight
        * determined by the NAAS using ethnicity and gender, age, state of residence, education, and nativity by a unique ranking method
* "ethnicity" 
    * Respondent's ethnicity
        * ranging from over 60 options from the AAPI and Latinx communities to specify country-specific heritage
* "racegroup" 
    * Respondent's race demographic
        * inclusive of Asian American (AA), Native Hawaiian or Pacific Islander (NHPI), White, Black, African American, Latinx, Native American, and Multiracial American
* "state" 
    + Respondent's state of residence
* "gender" 
    + Respondent's gender identity
        - inclusive of male, female, and other
* "education" 
    + Respondent's highest completed level of education
        - inclusive of no schooling completed, some schooling but no high school degree, high school degree or certificate, college degree or bachelor's degree, and graduate or professional degree
* "nativity1" 
    + Respondent's country of birth
        - if respondent reports AA or NHPI
* "nativity2" 
    + Respondent's country of birth
        - if respondent reports Latinx
* "legality" 
    + Respondent's immigration status
* "income1" 
    + Respondent's annual income
        - grouped by 10,000 USD
* "income2" 
    + Respondent's annual income
        - grouped by 50,000 USD
* "age1" 
    + Respondent's age group
        - based on whether the respondent is of the ages 18-34 or 35 and above
* "age2" 
    + Respondent's age

There were multiple versions of the income and age variables to provide enough levels of ambiguity for respondents such that they would feel comfortable consenting to release such information with the NAAS. For the majority of my analysis, I observed the data intersected by the "ethnicity" and the income variables.

## Pre-Election Survey

From the Pre-Election survey, I examined the following additional variables:

* "reg" 
    + Respondent's state of voter Registration
* "votepred" 
    + Respondent's intended candidate of choice for the 2016 Presidential Election
* "votelead" 
    + Respondent's lean towards a candidate of choice for the 2016 Presidential Election
* "party"
    + Respondent's political party affiliation
* "partycloser1"
    + Respondent's closeness with the Republican or the Democratic party
* "partycloser2"
    + Respondent's closeness with the Republican or the Democratic party based on party standing with political issues
* "favorbo"
    + Respondent's stance of favor with Barack Obama
* "favordt"
    + Respondent's stance of favor with Donald Trump
* "favorhc"
    + Respondent's stance of favor with Hillary Clinton
* "p1"
    + Respondent's policy view on "the health care law passed by Barack Obama and Congress in 2010"
* "p2"
    + Respondent's policy view on "major new spending by the federal government that would help undergraduates pay tuition at public colleges without needing loans"
* "p3"
    + Respondent's policy view on "accepting Syrian refugees into the United States"
* "p4"
    + Respondent's policy view on "legalizing the possession of small amounts of marijuana for personal use"
* "p5"
    + Respondent's policy view on "banning people who are Muslim from entering the United States"
* "p6"
    + Respondent's policy view on "setting stricter emission limits on power plants in order to address climate change"
* "p7"
    + Respondent's policy view on "the government doing more to give blacks equal rights with whites"
* "media1"
    + Respondent's method of getting information about politics
        - if respondent reports AA
* "media2"
    + Respondent's method of getting information about politics
        - if respondent reports NHPI
* "soc1"
    + Respondent's view on "the most important problem facing the United States today"
* "soc2"
    + Respondent's view on "the issue [that] is the most important to you personally"

## Post-Election Survey

reg = q2_3,
         vote = q2_4,
         voteres = q2_4a,
         party = pid4,
         partycloser1 = q10_0d,
         partycloser2 = q10_0e,
         favorbo = q2_2c,
         favordt = q2_2a,
         favorhc = q2_2b,
         contact1 = q2_6,
         contact2 = q2_7,
         e1 = q3_6_a,
         e2 = q3_6_b,
         e3 = q3_6_c,
         e4 = q3_6_d,
         e5 = q3_6_f,
         e6 = q3_6_g,
         i1 = q5_8_a,
         i2 = q5_8_b,
         i3 = q5_8_c,
         i4 = q5_8_d,
         mi1 = q5_1_b,
         mi2 = q5_1_c,
         mi3 = q5_1_d,
         mi4 = q5_1_e,
         mi5 = q5_1_g,
         mi6 = q5_1_h,
         mi7 = q5_1_i,
         mi8 = q5_1_j,
         mi9 = q5_1_k,
         ma1 = q5_2_a,
         ma2 = q5_2_b,
         ma3 = q5_2_c,
         ma4 = q5_2_d,
         ma5 = q5_2_e,
         ma6 = q5_2_f,
         ma7 = q5_2_g

# Results



## Pre-Election Survey

## Post-Election Survey

# Conclusion

As explored above, socioeconomic standing affects 
           
# References
